# Generated by Django 2.0.3 on 2018-03-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='auth_token',
            new_name='video_id',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='audio_data',
            field=models.CharField(default='{}', max_length=32768),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='video_data',
            field=models.CharField(default='{}', max_length=32768),
        ),
    ]
